### ISSUE TITLE
How to fix these problems?

### ISSUE THREAD

**Issue by MaxCaiLC** [w1710n0/device_xiaomi_sakura#1]
I encountered some issues while compiling using the device tree of the arrow branch. But I used the device tree of your other repository, but the problem did not occur

This is the error log:
[  2% 5/180] including art/Android.mk ...
Disabling ART_BUILD_TARGET_DEBUG
Disabling ART_BUILD_HOST_DEBUG
[ 83% 150/180] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:87: warning: Be careful when using the SELINUX_IGNORE_NEVERALLOWS flag. It does not work in user builds and using it will not stop you from failing CTS.
[ 99% 179/180] finishing build rules ...
FAILED: 
device/xiaomi/sakura/camera/QCamera2/Android.mk: error: "camera.msm8953 (SHARED_LIBRARIES android-arm) missing libts_face_beautify_hal (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
device/xiaomi/sakura/camera/QCamera2/Android.mk: error: "camera.msm8953 (SHARED_LIBRARIES android-arm) missing libts_detected_face_hal (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
device/xiaomi/sakura/libshims/Android.mk: error: "libqmiservices_shim (SHARED_LIBRARIES android-arm64) missing libqmiservices (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
device/xiaomi/sakura/libshims/Android.mk: error: "libqmiservices_shim (SHARED_LIBRARIES android-arm) missing libqmiservices (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:1125: error: exiting from previous errors.

**Comment by w1710n0** [comment]
Hi..thanks for your info..did you see the different among repository? As i
remember just drop that makes an error or you can find that missing.

**Comment by MaxCaiLC** [comment]
Good. I compared and determined the differences, I delete them.But it still can not work properly.So I give up.

**Comment by w1710n0** [comment]
But don't use that..just use the repo with prefix android_*
